- name: Install required dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: no

- name: Ensure /etc/apt/keyrings directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    group: root
    mode: '0755'
    
- name: Add Kubernetes GPG key for APT
  ansible.builtin.shell: 
    cmd: >
      curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key |
      gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Install gnupg if not present
  apt:
    name: gnupg
    state: present
    update_cache: yes

- name: Add Kubernetes APT repository
  apt_repository:
    repo: "deb [signed-by={{ keyring_path }}] {{ kubernetes_repo_url }} /"
    filename: kubernetes
    state: present

- name: Check if containerd is installed
  command: which containerd
  register: containerd_installed
  ignore_errors: true

- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker apt repository for Debian 11
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable"
    state: present

- name: Update apt cache after adding Docker repository
  apt:
    update_cache: yes

- name: Install containerd
  apt:
    name: containerd.io=1.6.*
    state: present
  when: containerd_installed.rc != 0

- name: Ensure /etc/containerd directory exists
  file:
    path: "{{ containerd_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  when: containerd_installed.rc != 0

- name: Generate default containerd config
  command: containerd config default
  register: containerd_config
  when: containerd_installed.rc != 0

- name: Write containerd config to /etc/containerd/config.toml
  copy:
    dest: "{{ containerd_config_file }}"
    content: "{{ containerd_config.stdout }}"
    owner: root
    group: root
    mode: '0644'
  when: containerd_installed.rc != 0

- name: Ensure SystemdCgroup is set to true
  ansible.builtin.lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^\s*SystemdCgroup\s*=\s*.*$'
    line: '            SystemdCgroup = true'
    backrefs: yes
  become: true
  when: containerd_installed.rc != 0

- name: Start and enable containerd service
  systemd:
    name: containerd
    state: started
    enabled: yes
  when: containerd_installed.rc != 0
