- name: config Kubernetes Master and Worker Nodes
  hosts: all
  become: true
  vars_files:
    - /inventory/hosts/es.ini
  roles:
    - common
    
- name: Install and Configure containerd on Debian
  hosts: all
  become: yes
  vars:
    containerd_version: "1.6.21"  
    docker_repo: "https://download.docker.com/linux/debian"
  roles:
    - containerd

- name: config Kubernetes Master Node
  hosts: k8s_master
  become: true
  roles:
    - kubelet
    - kubectl

- name: config Kubernetes Worker Node
  hosts: k8s_node
  become: true
  roles:
   - kubelet

- name: Initialize Kubernetes Control Plane
  hosts: k8s_master_1
  become: true
  roles:
    - initiialize